version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: niyukti_db
    restart: always
    environment:
      POSTGRES_USER: niyukti
      POSTGRES_PASSWORD: niyukti_password
      POSTGRES_DB: niyukti
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
